### ISSUE TITLE
git-splits contains carriage-return characters

### ISSUE THREAD

**Issue by mhaberler** [ajdruff/git-splits#1]
which leads to arcane errors like

fatal: 'splits' appears to be a git command, but we were not
able to execute it. Maybe git-splits is broken?

**Comment by rodonn** [comment]
An alternative fix on unix/osx is to run dos2unix to remove the dos style line endings.

e.g. on osx (using homebrew to install dos2unix)
`brew install dos2unix`
`dos2unix $(which git-splits)`

**Comment by ajdruff** [comment]
yes, thanks . i think more than a few issues/PRs mentioned this :) . fixed in latest release
