### ISSUE TITLE
Syntax error: Newline unexpected

### ISSUE THREAD

**Issue by BarbzYHOOL** [ajdruff/git-splits#7]
/usr/bin/git-splits: 8: /usr/bin/git-splits: Syntax error: newline unexpected

Dunno what to do

**Comment by BarbzYHOOL** [comment]
Lol, ok the wget downloaded the HTML on the page...

Instead I just copied the command code directly in the file.

Also the one line command is not good because of the lack of sudo.

Anyway awesome little tool

**Comment by BarbzYHOOL** [comment]
I think you guys can install it like this (for newbies):

git clone https://github.com/ajdruff/git-splits
cd git-splits
sudo cp git-splits $(dirname $(which git))/git-splits
sudo chmod o+x $(dirname $(which git))/git-splits

**Comment by BarbzYHOOL** [comment]
After that, you probably need to run "dos2unix" to convert the file for linux line endings.

Another method:
    wget -O $(dirname $(which git))/git-splits https://raw.githubusercontent.com/ajdruff/git-splits/master/git-splits
    chmod o+x $(dirname $(which git))/git-splits
    dos2unx $(dirname $(which git))/git-splits

**Comment by ajdruff** [comment]
> /usr/bin/git-splits: 8: /usr/bin/git-splits: Syntax error: newline unexpected
> 
> Dunno what to do
this was due to windows line endings. fixed this in latest update

**Comment by ajdruff** [comment]
> I think you guys can install it like this (for newbies):
> 
> git clone https://github.com/ajdruff/git-splits
> cd git-splits
> sudo cp git-splits $(dirname $(which git))/git-splits
> sudo chmod o+x $(dirname $(which git))/git-splits

I fixed the one-liner. It had a typo in the wget and was pointing to the wrong repo, AND it needs sudo.

**Comment by ajdruff** [comment]
> After that, you probably need to run "dos2unix" to convert the file for linux line endings.
> 
> Another method:
> wget -O $(dirname $(which git))/git-splits https://raw.githubusercontent.com/ajdruff/git-splits/master/git-splits
> chmod o+x $(dirname $(which git))/git-splits
> dos2unx $(dirname $(which git))/git-splits

yep, thanks,  thats what i ended up doing.

**Comment by ajdruff** [comment]
Thanks for your help and comments.

**Comment by BarbzYHOOL** [comment]
np
